// Generated by scripts/generate-gallery-image-seo.mjs from client/src/pages/Gallery.tsx.
// Run pnpm seo:gallery after changing galleryImages.
export const galleryImages = [
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/dukkhovilash-book-flowers.webp",
    "caption": "আমি বিচ্ছেদকে বলি দুঃখবিলাস — বই ও জবা ফুল",
    "addedAt": "2026-08-18T15:32:03Z"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/onubhuti-book-flowers.webp",
    "caption": "অনুভূতি — বই ও জবা ফুল",
    "addedAt": "2026-08-18T15:32:02Z"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/book-duo-flowers.webp",
    "caption": "অনুভূতি ও আমি বিচ্ছেদকে বলি দুঃখবিলাস — বইয়ের যুগল ফ্রেম",
    "addedAt": "2026-08-18T15:32:01Z"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/Photoroom_20260224_033915.webp",
    "caption": "লেখকের প্রতিকৃতি"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/edited_image_blazer.webp",
    "caption": "ব্লেজারে লেখক"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/bengali_olive_shirt_man_art.webp",
    "caption": "ইলাস্ট্রেটেড প্রতিকৃতি"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/bengali_sofa_man_art.webp",
    "caption": "ভাবনায় লেখক"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/Photoroom_20260105_192556.webp",
    "caption": "দুঃখবিলাস — প্রচ্ছদ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_63832.webp",
    "caption": "ফ্রন্ট টেক অফিসে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6494.webp",
    "caption": "দুঃখবিলাস — টেবিল সাজে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6021.webp",
    "caption": "কবিতার পাতা — পাঠ ১"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6015.webp",
    "caption": "কবিতার পাতা — পাঠ ২"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6032.webp",
    "caption": "কবিতার পাতা — পাঠ ৩"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/FullSizeRender.webp",
    "caption": "দুঃখবিলাস — বই, ফোন ও ফুল"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/FullSizeRender_01.webp",
    "caption": "দুঃখবিলাস — ফুলেল সাজে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/FullSizeRender_02.webp",
    "caption": "দুঃখবিলাস — হাতে ধরা"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_1743.webp",
    "caption": "দুঃখবিলাস — বই ও ফুল"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_5349.webp",
    "caption": "দুঃখবিলাস — প্রদর্শনীতে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_4706.webp",
    "caption": "সাদামাটা দিনে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_3070.webp",
    "caption": "অফিসে লেখক"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_3862.webp",
    "caption": "আয়োজনে উপস্থিতি"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_1014.webp",
    "caption": "আয়োজনে প্রতিকৃতি"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_2472.webp",
    "caption": "কাজের বিরতিতে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_9833.webp",
    "caption": "দুঃখবিলাস — প্রচ্ছদ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_9832.webp",
    "caption": "দুঃখবিলাস — স্টুডিও উপস্থাপনা"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_9830.webp",
    "caption": "দুঃখবিলাস — সম্পূর্ণ প্রচ্ছদ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_9832_01.webp",
    "caption": "দুঃখবিলাস — সাদা পটভূমিতে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/photo-output.webp",
    "caption": "প্রিয়জনের সঙ্গে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/Addalittlebitofbodytext.png.webp",
    "caption": "অফিসে প্রতিকৃতি"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6966.webp",
    "caption": "বাবা"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6969.webp",
    "caption": "ক্যাফেতে লেখক"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6967.webp",
    "caption": "ফ্রন্ট টেক অফিসে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6965.webp",
    "caption": "ফ্রন্ট টেক রিসেপশনে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6964.webp",
    "caption": "মরুভূমিতে লেখক"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6963.webp",
    "caption": "প্রকৃতির কোলে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6962.webp",
    "caption": "অফিস ডেস্কে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/IMG_6961.webp",
    "caption": "অফিসের অভ্যর্থনায়"
  },
  {
    "src": "https://d2xsxph8kpxj0f.cloudfront.net/310519663480075829/4WFGjMEZtwqeRWz2WqHMm4/profile_db5ff5d6.jpeg",
    "caption": "পেশাদার প্রতিকৃতি"
  },
  {
    "src": "https://d2xsxph8kpxj0f.cloudfront.net/310519663480075829/4WFGjMEZtwqeRWz2WqHMm4/profile2_57482935.jpg",
    "caption": "লেখার মুহূর্তে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/images/book-cover-20260328.jpg",
    "caption": "দুঃখবিলাস — ফুল ও বইয়ের সংগ্রহ"
  },
  {
    "src": "https://d2xsxph8kpxj0f.cloudfront.net/310519663480075829/4WFGjMEZtwqeRWz2WqHMm4/books-collection_0b763103.jpg",
    "caption": "দুঃখবিলাস — প্রকাশনা উপহার"
  },
  {
    "src": "https://d2xsxph8kpxj0f.cloudfront.net/310519663480075829/4WFGjMEZtwqeRWz2WqHMm4/writing1_9f5104e4.png",
    "caption": "কবিতার নকশা — ১"
  },
  {
    "src": "https://d2xsxph8kpxj0f.cloudfront.net/310519663480075829/4WFGjMEZtwqeRWz2WqHMm4/writing2_d3a49cae.jpg",
    "caption": "কবিতার নকশা — ২"
  },
  {
    "src": "https://d2xsxph8kpxj0f.cloudfront.net/310519663480075829/4WFGjMEZtwqeRWz2WqHMm4/book-photo_1173642f.jpg",
    "caption": "দুঃখবিলাস — ভালোবাসার উপহার"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_0665.JPG",
    "caption": "অভিমান — সাহিত্যিক পরিচিতি ও কবিতার পৃষ্ঠা"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_0517.JPG",
    "caption": "অভিমান — বইয়ের স্কয়ার মকআপ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_0518.JPG",
    "caption": "অভিমান — বইয়ের প্রচ্ছদ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_9830.JPG",
    "caption": "আমি বিচ্ছেদকে বলি দুঃখবিলাস — বইয়ের প্রচারচিত্র"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_9830_01.JPG",
    "caption": "দুঃখবিলাস — বইয়ের প্রচারচিত্রের কোলাজ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_9832.jpeg",
    "caption": "আমি বিচ্ছেদকে বলি দুঃখবিলাস — বইয়ের মকআপ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/IMG_3932.PNG",
    "caption": "ক্যামেরাসহ সৃজনের কর্মপরিসরে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/photo-output.png",
    "caption": "অভিমান — পাঠের মুহূর্তে"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/photo-output_01.png",
    "caption": "নারীকে সম্মান দিতে শিখুন — সাহিত্যিক উদ্ধৃতিচিত্র"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/book_cover_without_left_spine.png",
    "caption": "অভিমান — মূল বইয়ের প্রচ্ছদ"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/photo-output_02.png",
    "caption": "জীবন একটি ভ্রমণের চাপা রূপকথা — উদ্ধৃতিচিত্র"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/photo-output_03.png",
    "caption": "বিষাক্ত সাপের চেয়েও ভয়ংকর — উদ্ধৃতিচিত্র"
  },
  {
    "src": "https://www.mahbubsardarsabuj.com/photos/gallery-2026-08/photo-output_04.png",
    "caption": "মানুষ কখনো নিঃস্ব নয় — উদ্ধৃতিচিত্র"
  }
];
export const galleryPrimaryImage = galleryImages[0]?.src;
