name: Vercel Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_gHGJnuU9wkjtQNeHhYDyLiOy
          VERCEL_PROJECT_ID: prj_DMCIuDw3B7uMsgOjJajmd5yiyX2w

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_gHGJnuU9wkjtQNeHhYDyLiOy
          VERCEL_PROJECT_ID: prj_DMCIuDw3B7uMsgOjJajmd5yiyX2w

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_gHGJnuU9wkjtQNeHhYDyLiOy
          VERCEL_PROJECT_ID: prj_DMCIuDw3B7uMsgOjJajmd5yiyX2w
